import styled from "styled-components";
import { useFetchMatchDetails } from "../useFetchMatchDetails";
import MatchDetail from "./MatchDetail";
import { IMatchDetail } from "../type";

const MacthContainer = styled.div`
  border: 1px ${({ theme }) => theme.colors.border.main} solid;
  width: 100%;
  border-radius: 10px;
  background-color: ${({ theme }) => theme.colors.background.white};
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
`;

const CustomGameBtn = styled.div`
  margin-top: 15px;
  margin-bottom: 10px;
  width: 80%;
  border-radius: 15px;
  height: 40px;
  background-color: ${({ theme }) => theme.colors.brand.sky.main};
  display: flex;
  justify-content: center;
  align-items: center;
  color: ${({ theme }) => theme.colors.text.white};
  box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.3);
`;

const MatchDetailLoadingSkeleton = styled.div`
  width: 90%;
  height: 120px;
  background-color: ${({ theme }) => theme.colors.background.secondary};
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  opacity: 0.5;
  animation: pulse 1.5s infinite ease-in-out;

  @keyframes pulse {
    0% {
      opacity: 0.5;
    }
    50% {
      opacity: 1;
    }
    100% {
      opacity: 0.5;
    }
  }
`;

interface IMatchProps {
  userName: string;
  tagLine: string;
  puuid?: string;
}

export default function Match({ userName, tagLine, puuid }: IMatchProps) {
  const { matchDetails, isLoading } = useFetchMatchDetails(userName, tagLine);

  const dummyMatchDetails = [
    {
      info: {
        endOfGameResult: "GameComplete",
        gameDuration: 1804,
        gameStartTimestamp: 1734888858399,
        gameEndTimestamp: 1734890662694,
        gameMode: "CLASSIC",
        gameVersion: "14.24.644.2327",
        gameType: "MATCHED_GAME",
        queueId: 420,
        mapId: 11,
        platformId: "KR",
        participants: [
          {
            riotIdGameName: "Casting",
            riotIdTagline: "KR11",
            championName: "Jax",
            lane: "TOP",
            role: "SOLO",
            summonerLevel: 729,
            puuid:
              "styIjz7fwlQ4TkM9uJvZVzHZitVqTxw7Y14H-BodxYooVQP_Y3GpelVl35aV2FpE4X9oTP9hOK8lpw",
            championId: 24,
            champLevel: 15,
            item0: 2420,
            item1: 6610,
            item2: 0,
            item3: 3078,
            item4: 3111,
            item5: 0,
            item6: 3340,
            teamId: 100,
            win: true,
            kills: 4,
            deaths: 4,
            assists: 8,
            visionScore: 40,
            visionWardsBoughtInGame: 5,
            wardsPlaced: 17,
            wardsKilled: 3,
            detectorWardsPlaced: 5,
            totalMinionsKilled: 219,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 25050,
            totalDamageTaken: 34045,
            summoner1Id: 12,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 7,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8437,
                      var1: 1733,
                      var2: 1136,
                      var3: 0,
                    },
                    {
                      perk: 8446,
                      var1: 2659,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8444,
                      var1: 1967,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8451,
                      var1: 220,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 377,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.2075099,
              kda: 3.0,
              controlWardsPlaced: 5,
              damagePerMinute: 832.93115,
              gameLength: 1804.52,
              skillshotsDodged: 59,
              skillshotsHit: 0,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 1.3406547,
              goldPerMinute: 389.2554312459997,
            },
          },
          {
            riotIdGameName: "Hegzzz",
            riotIdTagline: "2020",
            championName: "Nidalee",
            lane: "JUNGLE",
            role: "NONE",
            summonerLevel: 269,
            puuid:
              "E7ji7T7eRFePRLxBqenF55WShB8SWubtzzDAXPpuTT78_mv_K8iNl3FKa8c36Xn2ICy2Rc8ZYyFYrQ",
            championId: 76,
            champLevel: 16,
            item0: 3020,
            item1: 3157,
            item2: 1082,
            item3: 2055,
            item4: 4628,
            item5: 6653,
            item6: 3363,
            teamId: 100,
            win: true,
            kills: 6,
            deaths: 4,
            assists: 17,
            visionScore: 36,
            visionWardsBoughtInGame: 5,
            wardsPlaced: 4,
            wardsKilled: 6,
            detectorWardsPlaced: 3,
            totalMinionsKilled: 25,
            neutralMinionsKilled: 181,
            totalDamageDealtToChampions: 26201,
            totalDamageTaken: 41891,
            summoner1Id: 4,
            summoner2Id: 11,
            dangerPings: 0,
            getBackPings: 9,
            holdPings: 0,
            needVisionPings: 1,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8010,
                      var1: 332,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9111,
                      var1: 2355,
                      var2: 460,
                      var3: 0,
                    },
                    {
                      perk: 9105,
                      var1: 12,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8017,
                      var1: 1197,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8210,
                      var1: 13,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8232,
                      var1: 5,
                      var2: 10,
                      var3: 0,
                    },
                  ],
                  style: 8200,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.33342078,
              kda: 5.75,
              controlWardsPlaced: 3,
              damagePerMinute: 871.18353,
              gameLength: 1804.52,
              skillshotsDodged: 40,
              skillshotsHit: 30,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 1.1986165,
              goldPerMinute: 413.5724275082931,
            },
          },
          {
            riotIdGameName: "Heru",
            riotIdTagline: "KR821",
            championName: "Sylas",
            lane: "MIDDLE",
            role: "DUO",
            summonerLevel: 941,
            puuid:
              "SiRGBNyPiT4yIvgcuxKXr5rfqm9yb-1fLzi0YDjW3mYKCE0EmWVydurU3y0RqqPtUzVP0P1XqDShHA",
            championId: 517,
            champLevel: 15,
            item0: 3152,
            item1: 4629,
            item2: 3157,
            item3: 1082,
            item4: 1057,
            item5: 3111,
            item6: 3364,
            teamId: 100,
            win: true,
            kills: 10,
            deaths: 5,
            assists: 10,
            visionScore: 27,
            visionWardsBoughtInGame: 3,
            wardsPlaced: 10,
            wardsKilled: 0,
            detectorWardsPlaced: 3,
            totalMinionsKilled: 174,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 32045,
            totalDamageTaken: 36812,
            summoner1Id: 12,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 16,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5008,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8010,
                      var1: 884,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8009,
                      var1: 3837,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9105,
                      var1: 17,
                      var2: 40,
                      var3: 0,
                    },
                    {
                      perk: 8017,
                      var1: 1320,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8444,
                      var1: 2199,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8451,
                      var1: 214,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.74088204,
              kda: 4.0,
              controlWardsPlaced: 3,
              damagePerMinute: 1065.4954,
              gameLength: 1804.52,
              skillshotsDodged: 37,
              skillshotsHit: 26,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 0.91892284,
              goldPerMinute: 427.7502038865075,
            },
          },
          {
            riotIdGameName: "Season of Leaves",
            riotIdTagline: "1031",
            championName: "Ashe",
            lane: "MIDDLE",
            role: "DUO",
            summonerLevel: 966,
            puuid:
              "D6cLuh0yjfRaEVL4ECFSWItU3hloPQq53iDeSdja3IPWs7YeR1x7Ue3gjw5qPw16tusFmiUEyay2Mg",
            championId: 22,
            champLevel: 16,
            item0: 3085,
            item1: 3139,
            item2: 6672,
            item3: 1055,
            item4: 3006,
            item5: 3033,
            item6: 3363,
            teamId: 100,
            win: true,
            kills: 9,
            deaths: 4,
            assists: 11,
            visionScore: 29,
            visionWardsBoughtInGame: 2,
            wardsPlaced: 11,
            wardsKilled: 4,
            detectorWardsPlaced: 2,
            totalMinionsKilled: 254,
            neutralMinionsKilled: 9,
            totalDamageDealtToChampions: 32726,
            totalDamageTaken: 21716,
            summoner1Id: 4,
            summoner2Id: 21,
            dangerPings: 0,
            getBackPings: 2,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8008,
                      var1: 2073,
                      var2: 2073,
                      var3: 0,
                    },
                    {
                      perk: 9101,
                      var1: 1747,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9104,
                      var1: 15,
                      var2: 30,
                      var3: 0,
                    },
                    {
                      perk: 8017,
                      var1: 1234,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 141,
                    },
                    {
                      perk: 8410,
                      var1: 185,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.0,
              kda: 5.0,
              controlWardsPlaced: 2,
              damagePerMinute: 1088.1575,
              gameLength: 1804.52,
              skillshotsDodged: 27,
              skillshotsHit: 79,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 0.99057645,
              goldPerMinute: 491.9713243207252,
            },
          },
          {
            riotIdGameName: "Happy",
            riotIdTagline: "day12",
            championName: "Nautilus",
            lane: "MIDDLE",
            role: "SUPPORT",
            summonerLevel: 665,
            puuid:
              "x7jOd5I-JQeDtzOgfDIcY_1UM_YLdbWI_WFV1DAey9NPs_2Oun-z6uXQpoUFJ51TM8G_QjhRQF8k4w",
            championId: 111,
            champLevel: 13,
            item0: 3869,
            item1: 3190,
            item2: 0,
            item3: 8020,
            item4: 3111,
            item5: 2055,
            item6: 3364,
            teamId: 100,
            win: true,
            kills: 2,
            deaths: 6,
            assists: 25,
            visionScore: 91,
            visionWardsBoughtInGame: 10,
            wardsPlaced: 43,
            wardsKilled: 8,
            detectorWardsPlaced: 9,
            totalMinionsKilled: 25,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 11260,
            totalDamageTaken: 24023,
            summoner1Id: 4,
            summoner2Id: 14,
            dangerPings: 0,
            getBackPings: 54,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5010,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8439,
                      var1: 459,
                      var2: 1535,
                      var3: 0,
                    },
                    {
                      perk: 8463,
                      var1: 1324,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8473,
                      var1: 414,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8242,
                      var1: 173,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8306,
                      var1: 3,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.12234303,
              kda: 4.5,
              controlWardsPlaced: 8,
              damagePerMinute: 374.40945,
              gameLength: 1804.52,
              skillshotsDodged: 53,
              skillshotsHit: 33,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 3.0403252,
              goldPerMinute: 288.52413787637454,
            },
          },
          {
            riotIdGameName: "海牛阿福的勇士",
            riotIdTagline: "666",
            championName: "Maokai",
            lane: "JUNGLE",
            role: "NONE",
            summonerLevel: 917,
            puuid:
              "AIj7y5io7HygpdyvINV3-dFePGo39IlNygwPJ7wEC13i81RtQohXqFrQSVLpFfsdQQe3YfbVpxo_eQ",
            championId: 57,
            champLevel: 16,
            item0: 2502,
            item1: 3065,
            item2: 3121,
            item3: 1057,
            item4: 3076,
            item5: 3111,
            item6: 3364,
            teamId: 200,
            win: false,
            kills: 3,
            deaths: 5,
            assists: 6,
            visionScore: 19,
            visionWardsBoughtInGame: 2,
            wardsPlaced: 10,
            wardsKilled: 2,
            detectorWardsPlaced: 2,
            totalMinionsKilled: 206,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 26528,
            totalDamageTaken: 44495,
            summoner1Id: 4,
            summoner2Id: 12,
            dangerPings: 0,
            getBackPings: 0,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5001,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8437,
                      var1: 1680,
                      var2: 1177,
                      var3: 0,
                    },
                    {
                      perk: 8446,
                      var1: 3178,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8444,
                      var1: 1815,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8453,
                      var1: 1558,
                      var2: 716,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 379,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.68571466,
              kda: 1.8,
              controlWardsPlaced: 2,
              damagePerMinute: 882.082,
              gameLength: 1804.52,
              skillshotsDodged: 66,
              skillshotsHit: 39,
              teamBaronKills: 1,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.6516307,
              goldPerMinute: 404.4333328780884,
            },
          },
          {
            riotIdGameName: "Sylvie",
            riotIdTagline: "77777",
            championName: "LeeSin",
            lane: "JUNGLE",
            role: "NONE",
            summonerLevel: 674,
            puuid:
              "nGn6qc3fNVyOCXIwp6djPHv2o57zTidr2kk_3MkLjT-hMp9V3lX8FPgbLp9aacQ9R85s1eCJclPmTQ",
            championId: 64,
            champLevel: 14,
            item0: 6610,
            item1: 3071,
            item2: 0,
            item3: 3155,
            item4: 0,
            item5: 3111,
            item6: 3340,
            teamId: 200,
            win: false,
            kills: 4,
            deaths: 6,
            assists: 7,
            visionScore: 31,
            visionWardsBoughtInGame: 6,
            wardsPlaced: 16,
            wardsKilled: 2,
            detectorWardsPlaced: 5,
            totalMinionsKilled: 11,
            neutralMinionsKilled: 149,
            totalDamageDealtToChampions: 17238,
            totalDamageTaken: 42654,
            summoner1Id: 11,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 6,
            holdPings: 0,
            needVisionPings: 1,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8010,
                      var1: 315,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9111,
                      var1: 920,
                      var2: 220,
                      var3: 0,
                    },
                    {
                      perk: 9104,
                      var1: 13,
                      var2: 50,
                      var3: 0,
                    },
                    {
                      perk: 8014,
                      var1: 335,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8304,
                      var1: 12,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.7957709,
              kda: 1.8333334,
              controlWardsPlaced: 5,
              damagePerMinute: 573.16907,
              gameLength: 1804.52,
              skillshotsDodged: 47,
              skillshotsHit: 26,
              teamBaronKills: 1,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 1.0486658,
              goldPerMinute: 327.6303633481445,
            },
          },
          {
            riotIdGameName: "DRX ucal",
            riotIdTagline: "2025",
            championName: "Aurora",
            lane: "MIDDLE",
            role: "SOLO",
            summonerLevel: 613,
            puuid:
              "oqDqVABwzqbS-lgV6R_c9kYi636_DdVY9qEVrH32yotkhIqR0jbZK7tlhv9vy5soxVoia_tmzAewcA",
            championId: 893,
            champLevel: 16,
            item0: 1058,
            item1: 3020,
            item2: 6655,
            item3: 4645,
            item4: 3135,
            item5: 1058,
            item6: 3364,
            teamId: 200,
            win: false,
            kills: 10,
            deaths: 5,
            assists: 6,
            visionScore: 25,
            visionWardsBoughtInGame: 2,
            wardsPlaced: 3,
            wardsKilled: 5,
            detectorWardsPlaced: 1,
            totalMinionsKilled: 249,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 29041,
            totalDamageTaken: 19574,
            summoner1Id: 12,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 23,
            holdPings: 0,
            needVisionPings: 1,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5008,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8229,
                      var1: 1252,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8226,
                      var1: 250,
                      var2: 676,
                      var3: 0,
                    },
                    {
                      perk: 8210,
                      var1: 26,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8237,
                      var1: 620,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8200,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8143,
                      var1: 1488,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8106,
                      var1: 5,
                      var2: 31,
                      var3: 0,
                    },
                  ],
                  style: 8100,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.69528353,
              kda: 3.2,
              controlWardsPlaced: 1,
              damagePerMinute: 965.61945,
              gameLength: 1804.52,
              skillshotsDodged: 36,
              skillshotsHit: 25,
              teamBaronKills: 1,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.84214306,
              goldPerMinute: 492.3519440481988,
            },
          },
          {
            riotIdGameName: "스컬지",
            riotIdTagline: "K T",
            championName: "Ezreal",
            lane: "BOTTOM",
            role: "CARRY",
            summonerLevel: 449,
            puuid:
              "O7H4KJR0VGbhcQowmh0gfWpIaDMJrSgg9T15fNKqWCcRNdvLc9Edb9pVNCGTqdtCZNvSFWAKPqNCew",
            championId: 81,
            champLevel: 15,
            item0: 1055,
            item1: 3042,
            item2: 3078,
            item3: 3158,
            item4: 6694,
            item5: 1038,
            item6: 3363,
            teamId: 200,
            win: false,
            kills: 5,
            deaths: 8,
            assists: 3,
            visionScore: 10,
            visionWardsBoughtInGame: 0,
            wardsPlaced: 8,
            wardsKilled: 1,
            detectorWardsPlaced: 0,
            totalMinionsKilled: 213,
            neutralMinionsKilled: 10,
            totalDamageDealtToChampions: 30147,
            totalDamageTaken: 26886,
            summoner1Id: 4,
            summoner2Id: 1,
            dangerPings: 0,
            getBackPings: 0,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8005,
                      var1: 1714,
                      var2: 1714,
                      var3: 0,
                    },
                    {
                      perk: 8009,
                      var1: 1900,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9105,
                      var1: 20,
                      var2: 20,
                      var3: 0,
                    },
                    {
                      perk: 8017,
                      var1: 1235,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8226,
                      var1: 250,
                      var2: 986,
                      var3: 0,
                    },
                    {
                      perk: 8210,
                      var1: 8,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8200,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.0,
              kda: 1.0,
              controlWardsPlaced: 0,
              damagePerMinute: 1002.41473,
              gameLength: 1804.52,
              skillshotsDodged: 95,
              skillshotsHit: 129,
              teamBaronKills: 1,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.36118543,
              goldPerMinute: 417.28907102015813,
            },
          },
          {
            riotIdGameName: "나는먼지",
            riotIdTagline: "KR11",
            championName: "Braum",
            lane: "BOTTOM",
            role: "SUPPORT",
            summonerLevel: 755,
            puuid:
              "wAy689TGgX-23Jbxftgc1A2ysvEeyOn6eTU1fwDrXXRgWB3Vgbt-t9ffzgv2P-u2AYSlq2ErwPegog",
            championId: 201,
            champLevel: 12,
            item0: 3190,
            item1: 2055,
            item2: 3869,
            item3: 3076,
            item4: 3067,
            item5: 3111,
            item6: 3364,
            teamId: 200,
            win: false,
            kills: 1,
            deaths: 7,
            assists: 14,
            visionScore: 91,
            visionWardsBoughtInGame: 15,
            wardsPlaced: 39,
            wardsKilled: 13,
            detectorWardsPlaced: 12,
            totalMinionsKilled: 45,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 9710,
            totalDamageTaken: 26239,
            summoner1Id: 14,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 17,
            holdPings: 0,
            needVisionPings: 2,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5010,
                offense: 5007,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8465,
                      var1: 1952,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8463,
                      var1: 1170,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8473,
                      var1: 424,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8242,
                      var1: 245,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 196,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.38511086,
              kda: 2.142857,
              controlWardsPlaced: 12,
              damagePerMinute: 322.8858,
              gameLength: 1804.52,
              skillshotsDodged: 141,
              skillshotsHit: 53,
              teamBaronKills: 1,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 3.0462992,
              goldPerMinute: 271.3694619405097,
            },
          },
        ],
        teams: [
          {
            bans: [
              {
                championId: 555,
                pickTurn: 1,
              },
              {
                championId: 69,
                pickTurn: 2,
              },
              {
                championId: 112,
                pickTurn: 3,
              },
              {
                championId: 42,
                pickTurn: 4,
              },
              {
                championId: 238,
                pickTurn: 5,
              },
            ],
            objectives: {
              baron: {
                first: false,
                kills: 0,
              },
              champion: {
                first: true,
                kills: 31,
              },
              dragon: {
                first: false,
                kills: 1,
              },
              horde: {
                first: false,
                kills: 3,
              },
              inhibitor: {
                first: true,
                kills: 1,
              },
              riftHerald: {
                first: true,
                kills: 1,
              },
              tower: {
                first: false,
                kills: 8,
              },
            },
            teamId: 100,
            win: true,
          },
          {
            bans: [
              {
                championId: 112,
                pickTurn: 6,
              },
              {
                championId: 72,
                pickTurn: 7,
              },
              {
                championId: -1,
                pickTurn: 8,
              },
              {
                championId: 799,
                pickTurn: 9,
              },
              {
                championId: 60,
                pickTurn: 10,
              },
            ],
            objectives: {
              baron: {
                first: true,
                kills: 1,
              },
              champion: {
                first: false,
                kills: 23,
              },
              dragon: {
                first: true,
                kills: 2,
              },
              horde: {
                first: true,
                kills: 3,
              },
              inhibitor: {
                first: false,
                kills: 0,
              },
              riftHerald: {
                first: false,
                kills: 0,
              },
              tower: {
                first: true,
                kills: 5,
              },
            },
            teamId: 200,
            win: false,
          },
        ],
      },
      metadata: {
        dataVersion: "2",
        matchId: "KR_7433158298",
        participants: [
          "styIjz7fwlQ4TkM9uJvZVzHZitVqTxw7Y14H-BodxYooVQP_Y3GpelVl35aV2FpE4X9oTP9hOK8lpw",
          "E7ji7T7eRFePRLxBqenF55WShB8SWubtzzDAXPpuTT78_mv_K8iNl3FKa8c36Xn2ICy2Rc8ZYyFYrQ",
          "SiRGBNyPiT4yIvgcuxKXr5rfqm9yb-1fLzi0YDjW3mYKCE0EmWVydurU3y0RqqPtUzVP0P1XqDShHA",
          "D6cLuh0yjfRaEVL4ECFSWItU3hloPQq53iDeSdja3IPWs7YeR1x7Ue3gjw5qPw16tusFmiUEyay2Mg",
          "x7jOd5I-JQeDtzOgfDIcY_1UM_YLdbWI_WFV1DAey9NPs_2Oun-z6uXQpoUFJ51TM8G_QjhRQF8k4w",
          "AIj7y5io7HygpdyvINV3-dFePGo39IlNygwPJ7wEC13i81RtQohXqFrQSVLpFfsdQQe3YfbVpxo_eQ",
          "nGn6qc3fNVyOCXIwp6djPHv2o57zTidr2kk_3MkLjT-hMp9V3lX8FPgbLp9aacQ9R85s1eCJclPmTQ",
          "oqDqVABwzqbS-lgV6R_c9kYi636_DdVY9qEVrH32yotkhIqR0jbZK7tlhv9vy5soxVoia_tmzAewcA",
          "O7H4KJR0VGbhcQowmh0gfWpIaDMJrSgg9T15fNKqWCcRNdvLc9Edb9pVNCGTqdtCZNvSFWAKPqNCew",
          "wAy689TGgX-23Jbxftgc1A2ysvEeyOn6eTU1fwDrXXRgWB3Vgbt-t9ffzgv2P-u2AYSlq2ErwPegog",
        ],
      },
    },
    {
      info: {
        endOfGameResult: "GameComplete",
        gameDuration: 929,
        gameStartTimestamp: 1734846020636,
        gameEndTimestamp: 1734846949782,
        gameMode: "CLASSIC",
        gameVersion: "14.24.644.2327",
        gameType: "MATCHED_GAME",
        queueId: 420,
        mapId: 11,
        platformId: "KR",
        participants: [
          {
            riotIdGameName: "머이런놈이",
            riotIdTagline: "KR2",
            championName: "Camille",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 105,
            puuid:
              "DnpTkpQYQNFBm3-ZEZ5LiYxLtvBap5h8xZPQNWPRhyn0GfIAMOW4gRUOUfsPb-7-QEigFPJT5zdoJg",
            championId: 164,
            champLevel: 10,
            item0: 1054,
            item1: 3078,
            item2: 1029,
            item3: 1083,
            item4: 0,
            item5: 2422,
            item6: 3363,
            teamId: 100,
            win: false,
            kills: 1,
            deaths: 5,
            assists: 1,
            visionScore: 8,
            visionWardsBoughtInGame: 0,
            wardsPlaced: 5,
            wardsKilled: 0,
            detectorWardsPlaced: 0,
            totalMinionsKilled: 100,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 7216,
            totalDamageTaken: 12126,
            summoner1Id: 12,
            summoner2Id: 14,
            dangerPings: 0,
            getBackPings: 4,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5008,
                offense: 5008,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8437,
                      var1: 505,
                      var2: 269,
                      var3: 0,
                    },
                    {
                      perk: 8401,
                      var1: 433,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8429,
                      var1: 22,
                      var2: 10,
                      var3: 9,
                    },
                    {
                      perk: 8451,
                      var1: 130,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8304,
                      var1: 10,
                      var2: 3,
                      var3: 0,
                    },
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 265,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.0,
              kda: 0.4,
              controlWardsPlaced: 0,
              damagePerMinute: 465.85458,
              gameLength: 929.45465,
              skillshotsDodged: 0,
              skillshotsHit: 3,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.52493364,
              goldPerMinute: 353.8285151732016,
            },
          },
          {
            riotIdGameName: "chillguys",
            riotIdTagline: "0602",
            championName: "Kindred",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 39,
            puuid:
              "JDE3yXBfzpVRMm3euLTBIMvGB-8ma7eF0OW6zkYut-oqsx7mqoUfUCHpy_rT2QCY7qGjbtx4KSmaEg",
            championId: 203,
            champLevel: 9,
            item0: 1101,
            item1: 1036,
            item2: 3078,
            item3: 1036,
            item4: 0,
            item5: 2422,
            item6: 3364,
            teamId: 100,
            win: false,
            kills: 1,
            deaths: 4,
            assists: 0,
            visionScore: 14,
            visionWardsBoughtInGame: 1,
            wardsPlaced: 5,
            wardsKilled: 3,
            detectorWardsPlaced: 1,
            totalMinionsKilled: 6,
            neutralMinionsKilled: 91,
            totalDamageDealtToChampions: 4869,
            totalDamageTaken: 15254,
            summoner1Id: 4,
            summoner2Id: 11,
            dangerPings: 0,
            getBackPings: 10,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8005,
                      var1: 351,
                      var2: 351,
                      var3: 0,
                    },
                    {
                      perk: 9111,
                      var1: 29,
                      var2: 20,
                      var3: 0,
                    },
                    {
                      perk: 9104,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8014,
                      var1: 93,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8304,
                      var1: 11,
                      var2: 1,
                      var3: 5,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.16684315,
              kda: 0.25,
              controlWardsPlaced: 1,
              damagePerMinute: 314.35132,
              gameLength: 929.45465,
              skillshotsDodged: 5,
              skillshotsHit: 12,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.92605275,
              goldPerMinute: 316.8510920090932,
            },
          },
          {
            riotIdGameName: "쭌 베",
            riotIdTagline: "KR1",
            championName: "Galio",
            lane: "NONE",
            role: "DUO",
            summonerLevel: 732,
            puuid:
              "ehN8lUoQqLMGh1ckmTOcwA2TaSUmDW-BqCdAkb576sAIhhGWDWZ9vFF9GezyZ0kAxsADGuOAKoHEsg",
            championId: 3,
            champLevel: 10,
            item0: 3047,
            item1: 2031,
            item2: 3068,
            item3: 3113,
            item4: 1056,
            item5: 0,
            item6: 3364,
            teamId: 100,
            win: false,
            kills: 2,
            deaths: 3,
            assists: 2,
            visionScore: 11,
            visionWardsBoughtInGame: 1,
            wardsPlaced: 4,
            wardsKilled: 2,
            detectorWardsPlaced: 1,
            totalMinionsKilled: 120,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 7973,
            totalDamageTaken: 10858,
            summoner1Id: 12,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 9,
            holdPings: 0,
            needVisionPings: 3,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5008,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8230,
                      var1: 10,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8275,
                      var1: 3,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8210,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8237,
                      var1: 394,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8200,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8473,
                      var1: 358,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8451,
                      var1: 136,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.65223503,
              kda: 1.3333334,
              controlWardsPlaced: 1,
              damagePerMinute: 514.7233,
              gameLength: 929.45465,
              skillshotsDodged: 56,
              skillshotsHit: 24,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.7639632,
              goldPerMinute: 367.95294564818715,
            },
          },
          {
            riotIdGameName: "Happy",
            riotIdTagline: "day12",
            championName: "Jhin",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 664,
            puuid:
              "x7jOd5I-JQeDtzOgfDIcY_1UM_YLdbWI_WFV1DAey9NPs_2Oun-z6uXQpoUFJ51TM8G_QjhRQF8k4w",
            championId: 202,
            champLevel: 8,
            item0: 1055,
            item1: 2031,
            item2: 3134,
            item3: 3047,
            item4: 1018,
            item5: 0,
            item6: 3340,
            teamId: 100,
            win: false,
            kills: 2,
            deaths: 5,
            assists: 0,
            visionScore: 12,
            visionWardsBoughtInGame: 3,
            wardsPlaced: 7,
            wardsKilled: 2,
            detectorWardsPlaced: 3,
            totalMinionsKilled: 89,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 8426,
            totalDamageTaken: 9594,
            summoner1Id: 4,
            summoner2Id: 21,
            dangerPings: 0,
            getBackPings: 5,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5008,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8128,
                      var1: 177,
                      var2: 6,
                      var3: 0,
                    },
                    {
                      perk: 8139,
                      var1: 410,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8138,
                      var1: 2,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8106,
                      var1: 2,
                      var2: 16,
                      var3: 0,
                    },
                  ],
                  style: 8100,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8014,
                      var1: 105,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8009,
                      var1: 388,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.0,
              kda: 0.4,
              controlWardsPlaced: 3,
              damagePerMinute: 543.97473,
              gameLength: 929.45465,
              skillshotsDodged: 60,
              skillshotsHit: 3,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 0.78832203,
              goldPerMinute: 322.48002284468885,
            },
          },
          {
            riotIdGameName: "Berrrrrr",
            riotIdTagline: "KR3",
            championName: "Poppy",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 872,
            puuid:
              "auC3p7n12fqcHPkoTmcOmllYz37xD_NIcZ8xrJPZGmv1iNQTJeD85jaan6fE_iNf95fvDrRMuVlZZA",
            championId: 78,
            champLevel: 8,
            item0: 1028,
            item1: 3877,
            item2: 2055,
            item3: 3066,
            item4: 3047,
            item5: 1031,
            item6: 3364,
            teamId: 100,
            win: false,
            kills: 1,
            deaths: 3,
            assists: 2,
            visionScore: 25,
            visionWardsBoughtInGame: 3,
            wardsPlaced: 12,
            wardsKilled: 2,
            detectorWardsPlaced: 2,
            totalMinionsKilled: 23,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 6770,
            totalDamageTaken: 8584,
            summoner1Id: 14,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 1,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5008,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 9923,
                      var1: 25,
                      var2: 55,
                      var3: 0,
                    },
                    {
                      perk: 8143,
                      var1: 351,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8136,
                      var1: 6,
                      var2: 12,
                      var3: 0,
                    },
                    {
                      perk: 8105,
                      var1: 24,
                      var2: 3,
                      var3: 0,
                    },
                  ],
                  style: 8100,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8306,
                      var1: 2,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.5917264,
              kda: 1.0,
              controlWardsPlaced: 2,
              damagePerMinute: 437.0778,
              gameLength: 929.45465,
              skillshotsDodged: 30,
              skillshotsHit: 0,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 0,
              visionScorePerMinute: 1.6741022,
              goldPerMinute: 285.8677331490514,
            },
          },
          {
            riotIdGameName: "1Jiang",
            riotIdTagline: "KR1",
            championName: "Jax",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 399,
            puuid:
              "_xOE7VeJAaGqAiqgtMN1KPa76gvQsKLNLic2nnaTH0K4ch_FT5ENXyI1fTVfnb80g3wf5tb2LiegBg",
            championId: 24,
            champLevel: 11,
            item0: 3078,
            item1: 6610,
            item2: 1055,
            item3: 3047,
            item4: 0,
            item5: 0,
            item6: 3340,
            teamId: 200,
            win: true,
            kills: 6,
            deaths: 2,
            assists: 0,
            visionScore: 15,
            visionWardsBoughtInGame: 2,
            wardsPlaced: 8,
            wardsKilled: 1,
            detectorWardsPlaced: 2,
            totalMinionsKilled: 124,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 12518,
            totalDamageTaken: 12611,
            summoner1Id: 4,
            summoner2Id: 12,
            dangerPings: 0,
            getBackPings: 0,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8437,
                      var1: 728,
                      var2: 377,
                      var3: 0,
                    },
                    {
                      perk: 8446,
                      var1: 2330,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8444,
                      var1: 904,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8451,
                      var1: 156,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 344,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.27892327,
              kda: 3.0,
              controlWardsPlaced: 2,
              damagePerMinute: 808.12823,
              gameLength: 929.45465,
              skillshotsDodged: 3,
              skillshotsHit: 0,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 1.0151261,
              goldPerMinute: 544.8009471444284,
            },
          },
          {
            riotIdGameName: "DRX kyeahoo",
            riotIdTagline: "0813",
            championName: "XinZhao",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 667,
            puuid:
              "QT7d1KyCTT2CgCOQ5JzHwX9Pq3adbabkyRjrlw23No5VGn8jmyjtF5rvxP4GNn_YPl4kXekyBHIZ-Q",
            championId: 5,
            champLevel: 10,
            item0: 3047,
            item1: 6610,
            item2: 1037,
            item3: 2055,
            item4: 0,
            item5: 0,
            item6: 3513,
            teamId: 200,
            win: true,
            kills: 0,
            deaths: 1,
            assists: 7,
            visionScore: 20,
            visionWardsBoughtInGame: 3,
            wardsPlaced: 4,
            wardsKilled: 4,
            detectorWardsPlaced: 2,
            totalMinionsKilled: 4,
            neutralMinionsKilled: 105,
            totalDamageDealtToChampions: 5687,
            totalDamageTaken: 18861,
            summoner1Id: 11,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 24,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5001,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8010,
                      var1: 124,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9111,
                      var1: 246,
                      var2: 140,
                      var3: 0,
                    },
                    {
                      perk: 9104,
                      var1: 10,
                      var2: 30,
                      var3: 0,
                    },
                    {
                      perk: 8299,
                      var1: 62,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8304,
                      var1: 9,
                      var2: 4,
                      var3: 5,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.60347587,
              kda: 7.0,
              controlWardsPlaced: 2,
              damagePerMinute: 367.14832,
              gameLength: 929.45465,
              skillshotsDodged: 5,
              skillshotsHit: 0,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 1.3086959,
              goldPerMinute: 368.9343364062019,
            },
          },
          {
            riotIdGameName: "헤이스트",
            riotIdTagline: "헤이스트",
            championName: "Pyke",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 1099,
            puuid:
              "oly02DNtd1VgN9mamzry9fm27RIyvkKaiJUBQ2Yg9awWudTQMtkDnDzPs8mreMcAZECz7yxUExHPNg",
            championId: 555,
            champLevel: 11,
            item0: 6698,
            item1: 2422,
            item2: 3142,
            item3: 1054,
            item4: 1029,
            item5: 0,
            item6: 3364,
            teamId: 200,
            win: true,
            kills: 11,
            deaths: 2,
            assists: 1,
            visionScore: 11,
            visionWardsBoughtInGame: 1,
            wardsPlaced: 5,
            wardsKilled: 3,
            detectorWardsPlaced: 1,
            totalMinionsKilled: 107,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 11335,
            totalDamageTaken: 11849,
            summoner1Id: 12,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 3,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 9923,
                      var1: 26,
                      var2: 72,
                      var3: 0,
                    },
                    {
                      perk: 8143,
                      var1: 415,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8138,
                      var1: 18,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8106,
                      var1: 4,
                      var2: 26,
                      var3: 0,
                    },
                  ],
                  style: 8100,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 223,
                    },
                    {
                      perk: 8304,
                      var1: 9,
                      var2: 4,
                      var3: 5,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.27942634,
              kda: 6.0,
              controlWardsPlaced: 1,
              damagePerMinute: 731.7712,
              gameLength: 929.45465,
              skillshotsDodged: 2,
              skillshotsHit: 15,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 0.75911814,
              goldPerMinute: 555.1681655762278,
            },
          },
          {
            riotIdGameName: "DRX kyeahoo",
            riotIdTagline: "0630",
            championName: "Varus",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 384,
            puuid:
              "TRtvzSyiXBeo0bW_vaceN6a9s8f9at923tEYmdz1AvuFqtsgF3Fry-oiazNMDlZkbeha2FwFFt844A",
            championId: 110,
            champLevel: 9,
            item0: 2031,
            item1: 3153,
            item2: 0,
            item3: 3006,
            item4: 1042,
            item5: 1055,
            item6: 3363,
            teamId: 200,
            win: true,
            kills: 2,
            deaths: 2,
            assists: 1,
            visionScore: 13,
            visionWardsBoughtInGame: 2,
            wardsPlaced: 8,
            wardsKilled: 1,
            detectorWardsPlaced: 2,
            totalMinionsKilled: 111,
            neutralMinionsKilled: 4,
            totalDamageDealtToChampions: 6837,
            totalDamageTaken: 7433,
            summoner1Id: 21,
            summoner2Id: 4,
            dangerPings: 0,
            getBackPings: 6,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5008,
                offense: 5005,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8008,
                      var1: 143,
                      var2: 143,
                      var3: 0,
                    },
                    {
                      perk: 9101,
                      var1: 236,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 9104,
                      var1: 15,
                      var2: 20,
                      var3: 0,
                    },
                    {
                      perk: 8017,
                      var1: 380,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8000,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8345,
                      var1: 3,
                      var2: 0,
                      var3: 254,
                    },
                    {
                      perk: 8347,
                      var1: 0,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8300,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.5562141,
              kda: 1.5,
              controlWardsPlaced: 2,
              damagePerMinute: 441.3711,
              gameLength: 929.45465,
              skillshotsDodged: 2,
              skillshotsHit: 33,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 0.87277555,
              goldPerMinute: 376.4925109461512,
            },
          },
          {
            riotIdGameName: "rosie",
            riotIdTagline: "0711",
            championName: "Alistar",
            lane: "NONE",
            role: "SUPPORT",
            summonerLevel: 186,
            puuid:
              "Mqe1o3_MGBi3w3VZl1iOAh7Ujm_Xsn2SGM1A5Jxb4jjsNpD2TBYzoyZyUv-S27LM5t4OHV4WSEEcoA",
            championId: 12,
            champLevel: 9,
            item0: 0,
            item1: 3190,
            item2: 3876,
            item3: 2031,
            item4: 3047,
            item5: 0,
            item6: 3364,
            teamId: 200,
            win: true,
            kills: 1,
            deaths: 0,
            assists: 12,
            visionScore: 28,
            visionWardsBoughtInGame: 4,
            wardsPlaced: 14,
            wardsKilled: 2,
            detectorWardsPlaced: 4,
            totalMinionsKilled: 22,
            neutralMinionsKilled: 0,
            totalDamageDealtToChampions: 3797,
            totalDamageTaken: 10720,
            summoner1Id: 4,
            summoner2Id: 14,
            dangerPings: 0,
            getBackPings: 2,
            holdPings: 0,
            needVisionPings: 0,
            perks: {
              statPerks: {
                defense: 5011,
                flex: 5010,
                offense: 5007,
              },
              styles: [
                {
                  description: "primaryStyle",
                  selections: [
                    {
                      perk: 8439,
                      var1: 267,
                      var2: 356,
                      var3: 0,
                    },
                    {
                      perk: 8463,
                      var1: 358,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8473,
                      var1: 407,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8451,
                      var1: 115,
                      var2: 0,
                      var3: 0,
                    },
                  ],
                  style: 8400,
                },
                {
                  description: "subStyle",
                  selections: [
                    {
                      perk: 8275,
                      var1: 7,
                      var2: 0,
                      var3: 0,
                    },
                    {
                      perk: 8232,
                      var1: 2,
                      var2: 10,
                      var3: 0,
                    },
                  ],
                  style: 8200,
                },
              ],
            },
            challenges: {
              controlWardTimeCoverageInRiverOrEnemyHalf: 0.5956788,
              kda: 13.0,
              controlWardsPlaced: 4,
              damagePerMinute: 245.12115,
              gameLength: 929.45465,
              skillshotsDodged: 0,
              skillshotsHit: 0,
              teamBaronKills: 0,
              teamElderDragonKills: 0,
              teamRiftHeraldKills: 1,
              visionScorePerMinute: 1.8226326,
              goldPerMinute: 401.59732813350985,
            },
          },
        ],
        teams: [
          {
            bans: [
              {
                championId: 64,
                pickTurn: 1,
              },
              {
                championId: 112,
                pickTurn: 2,
              },
              {
                championId: 234,
                pickTurn: 3,
              },
              {
                championId: 60,
                pickTurn: 4,
              },
              {
                championId: 42,
                pickTurn: 5,
              },
            ],
            objectives: {
              baron: {
                first: false,
                kills: 0,
              },
              champion: {
                first: false,
                kills: 7,
              },
              dragon: {
                first: false,
                kills: 0,
              },
              horde: {
                first: true,
                kills: 4,
              },
              inhibitor: {
                first: false,
                kills: 0,
              },
              riftHerald: {
                first: false,
                kills: 0,
              },
              tower: {
                first: false,
                kills: 1,
              },
            },
            teamId: 100,
            win: false,
          },
          {
            bans: [
              {
                championId: 111,
                pickTurn: 6,
              },
              {
                championId: 22,
                pickTurn: 7,
              },
              {
                championId: 7,
                pickTurn: 8,
              },
              {
                championId: 60,
                pickTurn: 9,
              },
              {
                championId: 76,
                pickTurn: 10,
              },
            ],
            objectives: {
              baron: {
                first: false,
                kills: 0,
              },
              champion: {
                first: true,
                kills: 20,
              },
              dragon: {
                first: true,
                kills: 2,
              },
              horde: {
                first: false,
                kills: 1,
              },
              inhibitor: {
                first: false,
                kills: 0,
              },
              riftHerald: {
                first: true,
                kills: 1,
              },
              tower: {
                first: true,
                kills: 3,
              },
            },
            teamId: 200,
            win: true,
          },
        ],
      },
      metadata: {
        dataVersion: "2",
        matchId: "KR_7431715275",
        participants: [
          "DnpTkpQYQNFBm3-ZEZ5LiYxLtvBap5h8xZPQNWPRhyn0GfIAMOW4gRUOUfsPb-7-QEigFPJT5zdoJg",
          "JDE3yXBfzpVRMm3euLTBIMvGB-8ma7eF0OW6zkYut-oqsx7mqoUfUCHpy_rT2QCY7qGjbtx4KSmaEg",
          "ehN8lUoQqLMGh1ckmTOcwA2TaSUmDW-BqCdAkb576sAIhhGWDWZ9vFF9GezyZ0kAxsADGuOAKoHEsg",
          "x7jOd5I-JQeDtzOgfDIcY_1UM_YLdbWI_WFV1DAey9NPs_2Oun-z6uXQpoUFJ51TM8G_QjhRQF8k4w",
          "auC3p7n12fqcHPkoTmcOmllYz37xD_NIcZ8xrJPZGmv1iNQTJeD85jaan6fE_iNf95fvDrRMuVlZZA",
          "_xOE7VeJAaGqAiqgtMN1KPa76gvQsKLNLic2nnaTH0K4ch_FT5ENXyI1fTVfnb80g3wf5tb2LiegBg",
          "QT7d1KyCTT2CgCOQ5JzHwX9Pq3adbabkyRjrlw23No5VGn8jmyjtF5rvxP4GNn_YPl4kXekyBHIZ-Q",
          "oly02DNtd1VgN9mamzry9fm27RIyvkKaiJUBQ2Yg9awWudTQMtkDnDzPs8mreMcAZECz7yxUExHPNg",
          "TRtvzSyiXBeo0bW_vaceN6a9s8f9at923tEYmdz1AvuFqtsgF3Fry-oiazNMDlZkbeha2FwFFt844A",
          "Mqe1o3_MGBi3w3VZl1iOAh7Ujm_Xsn2SGM1A5Jxb4jjsNpD2TBYzoyZyUv-S27LM5t4OHV4WSEEcoA",
        ],
      },
    },
  ];

  if (isLoading) {
    return (
      <MacthContainer>
        <CustomGameBtn>커스텀 게임 보러가기 -</CustomGameBtn>
        {Array.from({ length: 20 }).map((_, index) => (
          <MatchDetailLoadingSkeleton key={index} />
        ))}
      </MacthContainer>
    );
  }

  return (
    <MacthContainer>
      <CustomGameBtn>커스텀 게임 보러가기 -</CustomGameBtn>
      {matchDetails.map((matchDetail, index) => (
        <MatchDetail matchDetail={matchDetail} userPuuid={puuid} key={index} />
      ))}
    </MacthContainer>
  );
}
